# TreasureChests Configuration

# The chance (out of 1.0) that a treasure chest will drop when a valid block is broken.
# For example, 0.005 is a 0.5% chance.
drop-chance: 0.005

# The message sent to the player when they find a treasure chest.
# Use %player% as a placeholder for the player's name.
message: "&6&lTreasure Found! &eYou broke a block and discovered a hidden chest!"

# The sound played to the player when they find a treasure chest.
# A list of valid sounds can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound: "ENTITY_PLAYER_LEVELUP"

# A list of blocks that can drop a treasure chest when broken.
# A list of valid materials can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
allowed-blocks:
  - "STONE"
  - "DEEPSLATE"
  - "DIORITE"
  - "ANDESITE"
  - "GRANITE"

# loot-tables defines the loot found in treasure chests.
loot-tables:
  # 'rolls' determines how many times the plugin tries to add an item to the chest.
  # This can be a fixed number (e.g., 5) or a range (e.g., "3-6").
  rolls: "3-5"

  # Tiers define the different types of treasure chests that can be found.
  tiers:
    common:
      chance: 0.50
      items:
        - material: "IRON_INGOT"
          amount: "5-10"
          chance: 0.8
        - material: "BREAD"
          amount: "3-5"
          chance: 1.0
        - material: "COAL"
          amount: "4-8"
          chance: 0.9
    rare:
      chance: 0.25
      items:
        - material: "GOLDEN_APPLE"
          amount: 1
          chance: 0.7
        - material: "DIAMOND"
          amount: "1-3"
          chance: 0.5
        - material: "IRON_PICKAXE"
          amount: 1
          chance: 0.4
    epic:
      chance: 0.15
      items:
        - material: "DIAMOND_SWORD"
          amount: 1
          chance: 0.4
        - material: "TOTEM_OF_UNDYING"
          amount: 1
          chance: 0.2
        - material: "EXPERIENCE_BOTTLE"
          amount: "8-16"
          chance: 0.8
    legendary:
      chance: 0.08
      items:
        - material: "NETHERITE_INGOT"
          amount: "1-2"
          chance: 0.3
        - material: "ELYTRA"
          amount: 1
          chance: 0.1
        - material: "BEACON"
          amount: 1
          chance: 0.05
    mythical:
      chance: 0.02
      items:
        - material: "NETHER_STAR"
          amount: 1
          chance: 0.2
        - material: "ENCHANTED_GOLDEN_APPLE"
          amount: 1
          chance: 0.1
        - material: "DRAGON_EGG"
          amount: 1
          chance: 0.01
